[package]
name = "rust-crawler"
version = "0.1.0"
authors = ["Josh Caponigro <jcaponigro20@gmail.com>"]

[dependencies]
clap = "3.0"
indicatif = "0.17.8"
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.13"
url = "2.2"